### PR TITLE
[v12] Added IP pinning support for TLS routing behind ALB mode

### PR DESCRIPTION
**Pull request by greedy52**
backport #26623 to branch/v12

aka `proxy_service.trust_x_forwarded_for` support. Requested by customer for v12.

Note that this is for `proxy_listener_mode` set to `separate`, where the web port is served behind L7 LB but the rest of the ports are served by L4 LBs. In this case, TLS routing is only relevant for the web port, and requires `proxy_service.trust_x_forwarded_for`. PROXY protocol must also be enabled for other ports.

Tested with an ALB+NLB setup.

### CODE REVIEW

**Review by tigrato — APPROVED** [review]

**Review by AntonAM — APPROVED** [review]

**Review by smallinsky — COMMENTED** [review]
@greedy52 
Could you fix the UT merge issue:
```
lib/web/conn_upgrade_test.go:101:35: undefined: xForwardedFor (typecheck)
```

**Comment by greedy52** [comment]
> @greedy52 Could you fix the UT merge issue:
> 
> ```
> lib/web/conn_upgrade_test.go:101:35: undefined: xForwardedFor (typecheck)
> ```

Sorry, bad merged. Fixed now

**Review by smallinsky — APPROVED** [review]
